ZSH_CUSTOM=$HOME/.zsh-custom
source /usr/local/Cellar/antigen/1/antigen.zsh
 
# Load the Oh-My-ZSH core library
antigen-use oh-my-zsh

# Oh-My-ZSH plugins
if [ "$OSTYPE"="darwin11.0" ]; then antigen bundle osx; fi
 
# ZSH-Users plugins
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

# Custom plugins
antigen bundle ${ZSH_CUSTOM}/rbenv
antigen bundle ${ZSH_CUSTOM}/pyenv
antigen bundle ${ZSH_CUSTOM}/editor

antigen theme gnzh
 
antigen apply

